arch:
    - amd64
    - armv7l

services:
    - docker

script:
- docker build --build-arg BASE_ARCH=$TRAVIS_CPU_ARCH -t prytz/pipenv:$TRAVIS_CPU_ARCH-latest .
- docker manifest create prytz/pipenv:latest prytz/pipenv:$TRAVIS_CPU_ARCH-latest
- docker manifest annotate --arch $TRAVIS_CPU_ARCH prytz/pipenv:latest prytz/pipenv:$TRAVIS_CPU_ARCH-latest

deploy:
    skip_cleanup: true
    provider: script
    script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push prytz/pipenv:latest
    on:
        branch: master

after_deploy:
- rm -rf /home/travis/.docker/config.json